apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaartdijin-boodja-userdev
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-{{namespace}}-kaartdijin-boodja-userdev
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-{{namespace}}-kaartdijin-boodja-userdev	
    spec:
      initContainers:
          - name: file-permission-container
            image: busybox
            command: ["sh", "-c", "mkdir -p /mnt/storage/data; mkdir -p /mnt/storage/container ; chown -R 200000:20000 /mnt/storage/"]              
            volumeMounts:
              - name: kaartdijin-boodja-userdev
                mountPath: /mnt/storage/
            securityContext:
              runAsUser: 0 # Run as root user
              allowPrivilegeEscalation: true
      tolerations:
        - effect: NoSchedule
          key: kubernetes.azure.com/scalesetpriority
          operator: Equal
          value: spot                   
      containers:
        - env:
          envFrom:
            - secretRef:
                name: {{system}}-{{namespace}}-userdev
                optional: false      
          name: kaartdijin-boodja-userdev
          image: dbcawa/docker_app_dev:gis_kaartdijin_boodja_dev_latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: tcp8080
              protocol: TCP
          stdin: true          
          tty: true     
          volumeMounts:
            - mountPath: /data/
              name: kaartdijin-boodja-userdev
              subPath: data                  
            - mountPath: /home/container/
              name: kaartdijin-boodja-userdev
              subPath: container   
          workingDir: /data/data/projects/gis_kaartdijin_boodja/
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 10m
              memory: 1Gi          
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL          
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 200000           
      volumes:
        - name:  kaartdijin-boodja-userdev
          persistentVolumeClaim:
            claimName: kaartdijin-boodja-userdev
            
