apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{system}}-userdev-deny-all-ingress
  namespace: {{namespace}}   
spec:
  podSelector: {} 
  ingress: []
  policyTypes:
    - Ingress
