apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: geoserver_2_25-userdev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 12Gi
  storageClassName: managed-csi
