apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu2404-userdev
spec:
  replicas: 1
  strategy:
    type: Recreate  
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-{{namespace}}-ubuntu2404-userdev
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-{{namespace}}-ubuntu2404-userdev	
    spec:
      initContainers:
          - name: file-permission-container
            image: busybox
            command: ["sh", "-c", "mkdir -p /mnt/storage/data; mkdir -p /mnt/storage/container ; chown -R 200000:20000 /mnt/storage/"]              
            volumeMounts:
              - name: ubuntu2404-userdev
                mountPath: /mnt/storage/
            securityContext:
              runAsUser: 0 # Run as root user
              allowPrivilegeEscalation: true
      containers:
        - env:
          envFrom:
            - secretRef:
                name: {{system}}-{{namespace}}-userdev
                optional: false 
          name: ubuntu2404-userdev
          image: ghcr.io/dbca-wa/docker-apps-dev:ubuntu2404_dev_latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: tcp8080
              protocol: TCP
          stdin: true          
          tty: true     
          volumeMounts:
            - mountPath: /data/
              name: ubuntu2404-userdev
              subPath: data                  
            - mountPath: /home/container/
              name: ubuntu2404-userdev
              subPath: container   
          workingDir: /data/data/projects/ubuntu2404/
          resources:
            limits:
              cpu: '1'
              memory: 2Gi
            requests:
              cpu: 10m
              memory: 2Gi          
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL          
            privileged: false
            readOnlyRootFilesystem: false
            runAsNonRoot: true
            runAsUser: 200000           
      volumes:
        - name:  ubuntu2404-userdev
          persistentVolumeClaim:
            claimName: ubuntu2404-userdev
            
