apiVersion: v1
kind: Service
metadata:
  name: postgres16-userdev
spec:
  selector:
    workload.user.cattle.io/workloadselector: apps.deployment-{{namespace}}-postgres16-userdev
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432